name: Build Electron App

on:
  push:
    tags:
      - "v*.*.*" # Matches version tags like v1.0.0
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest # Can change to ubuntu-latest or macos-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v3

      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: ğŸ“¦ Install Dependencies
        run: npm install

      - name: âš’ï¸ Build Vite + Electron
        run: npm run build

      - name: ğŸ“¦ Package Electron App with Forge
        run: npm run make:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ—‚ Upload Built App
        uses: actions/upload-artifact@v4
        with:
          name: electron-build
          path: |
            out/make/zip/win32/x64/*.zip
            out/make/**/*.exe
            out/make/**/*.dmg

      - name: ğŸ“¦ Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/make/zip/win32/x64/*.zip
            out/make/**/*.exe
            out/make/**/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
